<a href="https://colab.research.google.com/github/YunSeoHwan/DNN_Base/blob/main/CH04/Gradient_simpleNet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **SimpleNet Gradient descent**

## **Define SimpleNet**

In [6]:
import sys, os
sys.path.append('/content/drive/MyDrive/Colab Notebooks/DNN_base/common/')
import numpy as np
from functions import softmax, cross_entropy_error
from gradient import numerical_gradient

In [7]:
class simpleNet:
    def __init__(self):
        self.W = np.random.randn(2, 3)  # 정규 분포에서 난수 생성

    def predict(self, x):
        return np.dot(x, self.W)

    def loss(self, x, t):
        z = self.predict(x)
        y = softmax(z)
        loss = cross_entropy_error(y, t)

        return loss

## **Result**

In [20]:
net = simpleNet()
print("Network Weight")
print(net.W)

x = np.array([0.6, 0.9])
p = net.predict(x)
print("\nPredict")
print(p)    # x dot W -> (1 x 2) (2 x 3) -> (1 x 3)

t = np.array([0, 0, 1])
l = net.loss(x, t)
print("\nLoss")
print(l)

Network Weight
[[ 2.33985046  0.21460797  1.36117277]
 [ 0.09003226 -0.88783281  0.37000278]]

Predict
[ 1.48493931 -0.67028475  1.14970616]

Loss
0.9401216724176118


In [22]:
def f(W):
    return net.loss(x, t)

In [23]:
dW = numerical_gradient(f, net.W)
print(dW)

[[ 0.32768101  0.03797077 -0.36565178]
 [ 0.49152152  0.05695615 -0.54847767]]
